/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CustomInput {
        /**
          * Handle the validatity constrain of input field
         */
        "isValid": boolean;
        /**
          * Define the type of Input Field e.g "url"
         */
        "label": string;
        /**
          * Define the size of input
         */
        "size": number;
        /**
          * Define the type of Input Field e.g "url"
         */
        "type": string;
        "validate": () => Promise<void>;
        /**
          * Define the pattern to validate the input field
         */
        "validationPattern": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLCustomInputElement extends Components.CustomInput, HTMLStencilElement {
    }
    var HTMLCustomInputElement: {
        prototype: HTMLCustomInputElement;
        new (): HTMLCustomInputElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "custom-input": HTMLCustomInputElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CustomInput {
        /**
          * Handle the validatity constrain of input field
         */
        "isValid"?: boolean;
        /**
          * Define the type of Input Field e.g "url"
         */
        "label"?: string;
        /**
          * This is the event for on user input
         */
        "onOnUserInput"?: (event: CustomEvent<any>) => void;
        /**
          * Define the size of input
         */
        "size"?: number;
        /**
          * Define the type of Input Field e.g "url"
         */
        "type"?: string;
        /**
          * Define the pattern to validate the input field
         */
        "validationPattern"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "custom-input": CustomInput;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "custom-input": LocalJSX.CustomInput & JSXBase.HTMLAttributes<HTMLCustomInputElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
